cap noi ado uninstall ccweight
cap noi ado uninstall rglm
cap noi ado uninstall bspline
cap noi ado uninstall bygap
cap noi ado uninstall ciform
cap noi ado uninstall dotex
cap noi ado uninstall explist
cap noi ado uninstall factext
cap noi ado uninstall factmerg
cap noi ado uninstall factref
cap noi ado uninstall gphepssj
cap noi ado uninstall gpreset
cap noi ado uninstall harmby
cap noi ado uninstall inccat
cap noi ado uninstall ingap
cap noi ado uninstall powercal
cap noi ado uninstall qrowname
cap noi ado uninstall strdate
cap noi ado uninstall xdatelist
cap noi ado uninstall lincomest
cap noi ado uninstall metaparm
cap noi ado uninstall pcontract
cap noi ado uninstall regaxis
cap noi ado uninstall senspec
cap noi ado uninstall smileplot
cap noi ado uninstall xcollapse
cap noi ado uninstall xcontract
cap noi ado uninstall bmjcip
cap noi ado uninstall descsave
cap noi ado uninstall dolog
cap noi ado uninstall dologx
cap noi ado uninstall dsconcat
cap noi ado uninstall eclplot
cap noi ado uninstall expgen
cap noi ado uninstall intext
cap noi ado uninstall keyby
cap noi ado uninstall lablist
cap noi ado uninstall listtex
cap noi ado uninstall parmest
cap noi ado uninstall rsource
cap noi ado uninstall scheme_rbn1mono
cap noi ado uninstall sdecode
cap noi ado uninstall sencode
cap noi ado uninstall somersd
cap noi ado uninstall stcmd
cap noi ado uninstall subsave
